export const START_LOAD_CHARACTERS = "START_LOAD_CHARACTERS";
export const LOADED_CHARACTERS = "LOADED_CHARACTERS";
export const ERROR_CHARACTERS = "ERROR_CHARACTERS";

export const START_LOAD_CHARACTERS_NEXT_PAGE = "START_LOAD_CHARACTERS_NEXT_PAGE";
export const LOADED_CHARACTERS_NEXT_PAGE = "LOADED_CHARACTERS_NEXT_PAGE";
export const ERROR_CHARACTERS_NEXT_PAGE = "ERROR_CHARACTERS_NEXT_PAGE";

export const START_LOAD_CHARACTERS_BY_SEARCH_PARAMS = "START_LOAD_CHARACTERS_BY_SEARCH_PARAMS";
export const LOADED_CHARACTERS_BY_SEARCH_PARAMS = "LOADED_CHARACTERS_BY_SEARCH_PARAMS";
export const ERROR_CHARACTERS_BY_SEARCH_PARAMS = "ERROR_CHARACTERS_BY_SEARCH_PARAMS";