export const START_LOAD_EPISODES = "START_LOAD_EPISODES";
export const LOADED_EPISODES = "LOADED_EPISODES";
export const ERROR_EPISODES = "ERROR_EPISODES";

export const START_LOAD_EPISODES_NEXT_PAGE = "START_LOAD_EPISODES_NEXT_PAGE";
export const LOADED_EPISODES_NEXT_PAGE = "LOADED_EPISODES_NEXT_PAGE";
export const ERROR_EPISODES_NEXT_PAGE = "ERROR_EPISODES_NEXT_PAGE";

export const START_LOAD_EPISODES_BY_SEARCH_PARAMS = "START_LOAD_EPISODES_BY_SEARCH_PARAMS";
export const LOADED_EPISODES_BY_SEARCH_PARAMS = "LOADED_EPISODES_BY_SEARCH_PARAMS";
export const ERROR_EPISODES_BY_SEARCH_PARAMS = "ERROR_EPISODES_BY_SEARCH_PARAMS";
