export const START_LOAD_LOCATIONS = "START_LOAD_LOCATIONS";
export const LOADED_LOCATIONS = "LOADED_LOCATIONS";
export const ERROR_LOCATIONS = "ERROR_LOCATIONS";

export const START_LOAD_LOCATIONS_NEXT_PAGE = "START_LOAD_LOCATIONS_NEXT_PAGE";
export const LOADED_LOCATIONS_NEXT_PAGE = "LOADED_LOCATIONS_NEXT_PAGE";
export const ERROR_LOCATIONS_NEXT_PAGE = "ERROR_LOCATIONS_NEXT_PAGE";

export const START_LOAD_LOCATIONS_BY_SEARCH_PARAMS = "START_LOAD_LOCATIONS_BY_SEARCH_PARAMS";
export const LOADED_LOCATIONS_BY_SEARCH_PARAMS = "LOADED_LOCATIONS_BY_SEARCH_PARAMS";
export const ERROR_LOCATIONS_BY_SEARCH_PARAMS = "ERROR_LOCATIONS_BY_SEARCH_PARAMS";