export const START_LOAD_CHARACTERS = "START_LOAD_CHARACTERS";
export const LOADED_CHARACTERS = "LOADED_CHARACTERS";
export const ERROR_CHARACTERS = "ERROR_CHARACTERS";

export const START_LOAD_CHARACTER = "START_LOAD_CHARACTER";
export const LOADED_CHARACTER = "LOADED_CHARACTER";
export const ERROR_CHARACTER = "ERROR_CHARACTER";