export const START_LOAD_CHARACTERS = "START_LOAD_CHARACTERS";
export const LOADED_CHARACTERS = "LOADED_CHARACTERS";
export const ERROR_CHARACTERS = "ERROR_CHARACTERS";

export const START_LOAD_CHARACTER = "START_LOAD_CHARACTER";
export const LOADED_CHARACTER = "LOADED_CHARACTER";
export const ERROR_CHARACTER = "ERROR_CHARACTER";

export const START_LOAD_LOCATIONS = "START_LOAD_LOCATIONS";
export const LOADED_LOCATIONS = "LOADED_LOCATIONS";
export const ERROR_LOCATIONS = "ERROR_LOCATIONS";

export const START_LOAD_LOCATION = "START_LOAD_LOCATION";
export const LOADED_LOCATION = "LOADED_LOCATION";
export const ERROR_LOCATION = "ERROR_LOCATION";