export const START_LOAD_CHARACTERS = "START_LOAD_CHARACTERS";
export const LOADED_CHARACTERS = "LOADED_CHARACTERS";
export const ERROR_CHARACTERS = "ERROR_CHARACTERS";

export const START_LOAD_CHARACTER = "START_LOAD_CHARACTER";
export const LOADED_CHARACTER = "LOADED_CHARACTER";
export const ERROR_CHARACTER = "ERROR_CHARACTER";

export const START_LOAD_LOCATIONS = "START_LOAD_LOCATIONS";
export const LOADED_LOCATIONS = "LOADED_LOCATIONS";
export const ERROR_LOCATIONS = "ERROR_LOCATIONS";

export const START_LOAD_LOCATION = "START_LOAD_LOCATION";
export const LOADED_LOCATION = "LOADED_LOCATION";
export const ERROR_LOCATION = "ERROR_LOCATION";

export const START_LOAD_EPISODES = "START_LOAD_EPISODES";
export const LOADED_EPISODES = "LOADED_EPISODES";
export const ERROR_EPISODES = "ERROR_EPISODES";

export const START_LOAD_EPISODE = "START_LOAD_EPISODE";
export const LOADED_EPISODE = "LOADED_EPISODE";
export const ERROR_EPISODE = "ERROR_EPISODE";

export const START_LOAD_NEXT_CHARACTERS_PAGE = "START_LOAD_NEXT_CHARACTERS_PAGE";
export const LOADED_NEXT_CHARACTERS_PAGE = "LOADED_NEXT_CHARACTERS_PAGE";
export const ERROR_NEXT_CHARACTERS_PAGE = "ERROR_NEXT_CHARACTERS_PAGE";

export const START_LOAD_NEXT_LOCATIONS_PAGE = "START_LOAD_NEXT_LOCATIONS_PAGE";
export const LOADED_NEXT_LOCATIONS_PAGE = "LOADED_NEXT_LOCATIONS_PAGE";
export const ERROR_NEXT_LOCATIONS_PAGE = "ERROR_NEXT_LOCATIONS_PAGE";

export const START_LOAD_NEXT_EPISODES_PAGE = "START_LOAD_NEXT_EPISODES_PAGE";
export const LOADED_NEXT_EPISODES_PAGE = "LOADED_NEXT_EPISODES_PAGE";
export const ERROR_NEXT_EPISODES_PAGE = "ERROR_NEXT_EPISODES_PAGE";

export const START_LOAD_CHARACTERS_BY_SEARCH_PARAMS = "START_LOAD_CHARACTERS_BY_SEARCH_PARAMS";
export const LOADED_CHARACTERS_BY_SEARCH_PARAMS = "LOADED_CHARACTERS_BY_SEARCH_PARAMS";
export const ERROR_CHARACTERS_BY_SEARCH_PARAMS = "ERROR_CHARACTERS_BY_SEARCH_PARAMS";

export const START_LOAD_LOCATIONS_BY_SEARCH_PARAMS = "START_LOAD_LOCATIONS_BY_SEARCH_PARAMS";
export const LOADED_LOCATIONS_BY_SEARCH_PARAMS = "LOADED_LOCATIONS_BY_SEARCH_PARAMS";
export const ERROR_LOCATIONS_BY_SEARCH_PARAMS = "ERROR_LOCATIONS_BY_SEARCH_PARAMS";

export const START_LOAD_EPISODES_BY_SEARCH_PARAMS = "START_LOAD_EPISODES_BY_SEARCH_PARAMS";
export const LOADED_EPISODES_BY_SEARCH_PARAMS = "LOADED_EPISODES_BY_SEARCH_PARAMS";
export const ERROR_EPISODES_BY_SEARCH_PARAMS = "ERROR_EPISODES_BY_SEARCH_PARAMS";